
DELETE FROM AE
WHERE SUBJID IS NULL;

DELETE FROM IE
WHERE SUBJID IS NULL;

UPDATE AE
SET AE_START_DATE = CAST(AE_START_DATE AS DATE);
UPDATE AE
SET AE_END_DATE = CAST(AE_END_DATE AS DATE);

UPDATE DA
SET DA_DATE = CAST(DA_DATE AS DATE);

UPDATE AE
SET AE_SEVERITY = UPPER(AE_SEVERITY);

UPDATE rando
SET `GROUP` = LOWER(`GROUP`);

SELECT 
    AE.SUBJID, rando.SUBJID, AE_START_DATE, AE_SEVERITY,
    IE_REASON, rando.GROUP
FROM 
    AE
INNER JOIN 
    IE ON AE.SUBJID = IE.SUBJID 
INNER JOIN 
    rando ON AE.SUBJID = rando.SUBJID;
    
    SELECT 
    SUBJID, COUNT(*) AS num_AE
FROM 
    AE
GROUP BY 
    SUBJID;
    
SELECT 
    rando.SUBJID, RANDO.GROUP,
    AE.AE_START_DATE, AE.AE_SEVERITY,
    IE.IE_REASON,
    DA.DA_DOSE, DA.DA_DATE,
    pk_pd.PK_CONCENTRATION, pk_pd.PK_SAMPLE_TIME
FROM 
    RANDO
LEFT JOIN 
    AE ON RANDO.SUBJID = AE.SUBJID
LEFT JOIN 
    IE ON RANDO.SUBJID = IE.SUBJID
LEFT JOIN 
    DA ON RANDO.SUBJID = DA.SUBJID
LEFT JOIN 
    pk_pd ON RANDO.SUBJID = pk_pd.SUBJID;